name: Run Python and PLC Script

on:
  push:
    branches:
      - main

jobs:
  run-python-and-ssh:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Скачиваем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Локальный Python скрипт
      - name: Run local Python script
        run: python main.py

      - name: Add PLC to known_hosts
        run: |
          echo "Creating .ssh directory"
          mkdir -p /home/runner/.ssh
          ssh-keyscan -T 10 -t rsa ${{ secrets.PLC_HOST }} >> /home/runner/.ssh/known_hosts
          chmod 644 /home/runner/.ssh/known_hosts

      # 4️⃣ SSH на ПЛК и запуск скрипта
      - name: SSH into PLC and run script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PLC_HOST }}
          username: ${{ secrets.PLC_USER }}
          password: ${{ secrets.PLC_PASSWORD }}
          script: |
            python3 /home/root/scripts/somth.py